spring.application.name=ecommerce-inventory-management

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=9890
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update               # dev-friendly; use flyway/liquibase in prod
spring.jpa.show-sql=true               # logs SQL in console
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
